# Generated by Django 3.1.6 on 2021-03-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=256)),
                ('maxSubmissions', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('maxSelections', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('submissionDateStart', models.DateTimeField()),
                ('submissionDateEnd', models.DateTimeField()),
                ('selectionDateStart', models.DateTimeField()),
                ('selectionDateEnd', models.DateTimeField()),
                ('classificationDateStart', models.DateTimeField()),
                ('classificationDateEnd', models.DateTimeField()),
                ('birthDateLimit', models.DateTimeField()),
            ],
            options={
                'ordering': ['submissionDateStart'],
            },
        ),
        migrations.CreateModel(
            name='gestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
