# Generated by Django 3.1.6 on 2021-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='birthDateLimit',
            field=models.DateTimeField(verbose_name='Limite data di nascita (i racconti inviati da autori nati prima di questa data saranno classificati nella categoria Senior)'),
        ),
        migrations.AlterField(
            model_name='events',
            name='classificationDateEnd',
            field=models.DateTimeField(verbose_name='Data fine classificazione racconti'),
        ),
        migrations.AlterField(
            model_name='events',
            name='classificationDateStart',
            field=models.DateTimeField(verbose_name='Data inizio classificazione racconti'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventName',
            field=models.CharField(max_length=256, verbose_name='Titolo concorso'),
        ),
        migrations.AlterField(
            model_name='events',
            name='maxSelections',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Numero massimo di racconti selezionabili'),
        ),
        migrations.AlterField(
            model_name='events',
            name='maxSubmissions',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Numero massimo di racconti inviabili'),
        ),
        migrations.AlterField(
            model_name='events',
            name='selectionDateEnd',
            field=models.DateTimeField(verbose_name='Data fine selezioni racconti'),
        ),
        migrations.AlterField(
            model_name='events',
            name='selectionDateStart',
            field=models.DateTimeField(verbose_name='Data inizio selezioni racconti'),
        ),
        migrations.AlterField(
            model_name='events',
            name='submissionDateEnd',
            field=models.DateTimeField(verbose_name='Data fine invio racconti'),
        ),
        migrations.AlterField(
            model_name='events',
            name='submissionDateStart',
            field=models.DateTimeField(verbose_name='Data inizio invio racconti'),
        ),
    ]
