# Generated by Django 3.1.6 on 2021-03-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestore', '0002_auto_20210305_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('operationDate', models.DateTimeField()),
                ('roleUser', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
