# Generated by Django 3.1.6 on 2021-03-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racconti',
            options={'ordering': ['-counter']},
        ),
    ]
