# Generated by Django 3.1.6 on 2021-03-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestore', '0001_initial'),
        ('autore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='valutatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.EmailField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('forename', models.CharField(max_length=64)),
                ('idEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestore.events')),
            ],
            options={
                'ordering': ['-idUser'],
            },
        ),
        migrations.CreateModel(
            name='valutazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('ranking', models.IntegerField()),
                ('idRacconto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raccontovalutazione', to='autore.racconti')),
                ('idValutatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutatorevalutazione', to='valutatore.valutatore')),
            ],
            options={
                'ordering': ['-idRacconto'],
            },
        ),
    ]
