# Generated by Django 3.1.6 on 2021-03-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestore', '0002_auto_20210305_1654'),
        ('valutatore', '0002_auto_20210305_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valutatore',
            name='idEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutatoriconcorso', to='gestore.events'),
        ),
    ]
